
const SHEET_WEB_APP_URL = "https://script.google.com/macros/s/AKfycbwpfLkue5ySQZJYmsAjorSw3mZNULTC_Vc_9Dnp5PY/dev";
const DEFAULT_DURATION_SEC = 45 * 60;
function normalizeAnswer(s){return (s||"").toString().trim().toLowerCase().replace(/\s+/g,"").replace(/,/g,".").replace(/×/g,"*");}
function shuffle(a){const arr=[...a];for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]];}return arr;}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36);}
function key(base,name,cls){return `${base}__${name}__${cls}`;}
function getAttempt(name,cls){const k=key("attempt",name,cls);const n=parseInt(localStorage.getItem(k)||"0",10);return n+1;}
function bumpAttempt(name,cls){const k=key("attempt",name,cls);const n=parseInt(localStorage.getItem(k)||"0",10);localStorage.setItem(k,String(n+1));}
function getUsed(name,cls){const k=key("usedIds",name,cls);try{return JSON.parse(localStorage.getItem(k)||"[]");}catch{return[];}}
function pushUsed(name,cls,ids){const k=key("usedIds",name,cls);const old=getUsed(name,cls);const merged=Array.from(new Set([...old,...ids]));localStorage.setItem(k,JSON.stringify(merged));}
let ALL=[],SELECTED=[],ANSWERS={},REMAIN=DEFAULT_DURATION_SEC,TIMER=null,RUN={name:"",cls:"",attempt:1,startedAt:0,runId:""};
async function bootstrap(){document.getElementById("startBtn").addEventListener("click",onStart);document.getElementById("submitBtn").addEventListener("click",onSubmit);document.getElementById("retryBtn").addEventListener("click",onRetry);document.getElementById("saveDraftBtn").addEventListener("click",onSaveDraft);const res=await fetch("questions.json?ts="+Date.now());ALL=await res.json();}
document.addEventListener("DOMContentLoaded",bootstrap);
function onStart(){const name=document.getElementById("studentName").value.trim();const cls=document.getElementById("studentClass").value.trim();let count=parseInt(document.getElementById("questionCount").value||"40",10);if(!name||!cls)return alert("Vui lòng nhập Họ và tên và chọn Lớp.");if(count<10)count=10;if(count>60)count=60;RUN={name,cls,attempt:getAttempt(name,cls),startedAt:Date.now(),runId:uid()};document.getElementById("who").textContent=name;document.getElementById("whichClass").textContent=cls;document.getElementById("attemptNo").textContent=RUN.attempt;const used=new Set(getUsed(name,cls));const poolNew=ALL.filter(q=>!used.has(q.id));SELECTED=(poolNew.length>=count?shuffle(poolNew):shuffle([...poolNew,...ALL])).slice(0,count);document.getElementById("loginCard").classList.add("hidden");document.getElementById("examStatus").classList.remove("hidden");document.getElementById("examCard").classList.remove("hidden");renderQuestions();startTimer(DEFAULT_DURATION_SEC);}
function renderQuestions(){const wrap=document.getElementById("questionsWrap");wrap.innerHTML="";ANSWERS={};SELECTED.forEach((q,idx)=>{const card=document.createElement("div");card.className="border rounded-xl p-4";const title=document.createElement("div");title.className="font-semibold";title.innerHTML=`Câu ${idx+1}. ${q.question}`;const input=document.createElement("input");input.type="text";input.className="w-full border rounded-lg px-3 py-2 mt-2";input.placeholder="Nhập đáp án...";input.dataset.qid=q.id;input.addEventListener("input",(e)=>{ANSWERS[q.id]=e.target.value;});const tools=document.createElement("div");tools.className="mt-2 flex items-center gap-3 text-sm";const hintBtn=document.createElement("button");hintBtn.className="px-2 py-1 rounded bg-gray-100 hover:bg-gray-200";hintBtn.textContent="Gợi ý";const hint=document.createElement("div");hint.className="hint text-gray-600 mt-1";hint.innerHTML=`<b>Gợi ý:</b> ${q.hint||"Ôn lại định nghĩa/qui tắc của bài này."}`;hintBtn.addEventListener("click",()=>hint.classList.toggle("show"));const topic=document.createElement("span");topic.className="text-gray-500";topic.textContent=`Chủ đề: ${q.topic}`;tools.appendChild(hintBtn);tools.appendChild(topic);card.appendChild(title);card.appendChild(input);card.appendChild(tools);card.appendChild(hint);wrap.appendChild(card);});}
function startTimer(seconds){REMAIN=seconds;updateClock();if(TIMER)clearInterval(TIMER);TIMER=setInterval(()=>{REMAIN--;updateClock();if(REMAIN<=0){clearInterval(TIMER);autoSubmit();}},1000);}
function updateClock(){const m=Math.floor(Math.max(REMAIN,0)/60).toString().padStart(2,"0");const s=Math.floor(Math.max(REMAIN,0)%60).toString().padStart(2,"0");document.getElementById("timeLeft").textContent=`${m}:${s}`;}
function onSaveDraft(){const k=key("draft",RUN.name,RUN.cls);const draft={answers:ANSWERS,remain:REMAIN,selectedIds:SELECTED.map(q=>q.id)};localStorage.setItem(k,JSON.stringify(draft));alert("Đã lưu nháp tại trình duyệt.");}
function autoSubmit(){alert("Hết giờ! Hệ thống tự nộp.");onSubmit();}
async function onSubmit(){let correct=0;const wrongTopicCounts={};const selectedIds=SELECTED.map(q=>q.id);SELECTED.forEach(q=>{const ua=normalizeAnswer(ANSWERS[q.id]||""),ans=normalizeAnswer(q.answer||"");const ok=ua===ans;if(ok)correct++;else wrongTopicCounts[q.topic]=(wrongTopicCounts[q.topic]||0)+1;});const total=SELECTED.length;const score=correct*0.25;const takenSec=Math.max(0,DEFAULT_DURATION_SEC-REMAIN);const topWrong=Object.entries(wrongTopicCounts).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([t,c])=>`${t} (${c})`);const suggestText=topWrong.length?("Nên ôn lại: "+topWrong.join(", ")):"Rất tốt! Bạn làm đúng hầu hết câu hỏi.";document.getElementById("examCard").classList.add("hidden");document.getElementById("resultCard").classList.remove("hidden");document.getElementById("score").textContent=`Điểm: ${score.toFixed(2)} / 10 (Đúng ${correct}/${total})`;document.getElementById("suggest").textContent=suggestText;pushUsed(RUN.name,RUN.cls,selectedIds);bumpAttempt(RUN.name,RUN.cls);try{await fetch(SHEET_WEB_APP_URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"application/json"},body:JSON.stringify({runId:RUN.runId,name:RUN.name,class:RUN.cls,attempt:RUN.attempt,score,correct,total,timeTakenSec:takenSec,remainSec:REMAIN,selectedIds:selectedIds.join(","),wrongTopics:topWrong.join(",")})});}catch(e){console.warn("Send sheet error",e);}}
function onRetry(){document.getElementById("resultCard").classList.add("hidden");document.getElementById("examCard").classList.remove("hidden");document.getElementById("examStatus").classList.remove("hidden");RUN.attempt=getAttempt(RUN.name,RUN.cls);document.getElementById("attemptNo").textContent=RUN.attempt;const count=parseInt(document.getElementById("questionCount").value||"40",10);const used=new Set(getUsed(RUN.name,RUN.cls));const poolNew=ALL.filter(q=>!used.has(q.id));SELECTED=(poolNew.length>=count?shuffle(poolNew):shuffle([...poolNew,...ALL])).slice(0,count);renderQuestions();startTimer(DEFAULT_DURATION_SEC);}
